language: elixir

elixir: 1.7.0
otp_release: 21.0

dist: xenial

env:
  - CODECOV_TOKEN="dbd14b32-89c9-4468-9074-93a982b021c9" DB_HOST=localhost DB_USER=postgres DB_PASSWORD= MIX_ENV=test

services:
  - postgresql

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

script:
  - mix do compile, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - _build
    - assets/node_modules
    - deps
