language: elixir

elixir: 1.7.0
otp_release: 21.0

dist: xenial
sudo: required

env:
  - CODECOV_TOKEN="dbd14b32-89c9-4468-9074-93a982b021c9" DB_HOST=localhost DB_USER=postgres DB_PASSWORD= MIX_ENV=test

services:
  - postgresql

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - mix local.rebar --force
  - mix local.hex --force

install:
  - mix deps.get
  - cd assets && yarn install && cd ../

script:
  - mix do compile, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  yarn: true
  directories:
    - _build
    - assets/node_modules
    - deps
